//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestHNN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comentario
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public int Solicitante { get; set; }
        public int Requerimiento { get; set; }
    
        public virtual Requerimiento Requerimiento1 { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
